[package]
name = "u128_binrel"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
path = "src/u128_binrel.rs"

[features]
certora = []

[dependencies]
solana-program = "2.2.1"
cvlr = "0.4"
cvlr-solana = "0.5"

[package.metadata.certora]
sources = ["Cargo.toml", "src/**/*.rs"]
solana_inlining = ["./cvt_inlining_core.txt"]
solana_summaries = ["./cvt_summaries_core.txt"]