mod native_math;
use cvlr::prelude::*;
use native_math::NativeSignedMath;
use native_math::NativeUnsignedMath;
use paste::paste;

macro_rules! bin_equiv {
    ($int_type:ty, $rust_fn:ident) => {
        paste! {
            #[rule]
            pub fn [<$rust_fn _ $int_type>]() {
                let x: $int_type = nondet();
                let y: $int_type = nondet();
                let rust = x.$rust_fn(y);
                let native = x.[<n_ $rust_fn>](y);
                clog!(x, y);
                cvlr_assert_eq!(rust, native);
            }
        }
    };
}

macro_rules! un_equiv {
    ($int_type:ty, $rust_fn:ident) => {
        paste! {
            #[rule]
            pub fn [<$rust_fn _ $int_type>]() {
                let x: $int_type = nondet();
                let rust = x.$rust_fn();
                let native = x.[<n_ $rust_fn>]();
                clog!(x);
                cvlr_assert_eq!(rust, native);
            }
        }
    };
}

macro_rules! for_signed {
    ($equiv:ident, $rust_fn:ident) => {
        $equiv!(i64, $rust_fn);
        $equiv!(i128, $rust_fn);
    };
}

macro_rules! for_unsigned {
    ($equiv:ident, $rust_fn:ident) => {
        $equiv!(u64, $rust_fn);
        $equiv!(u128, $rust_fn);
    };
}

macro_rules! for_all {
    ($equiv:ident, $rust_fn:ident) => {
        for_signed!($equiv, $rust_fn);
        for_unsigned!($equiv, $rust_fn);
    };
}

for_all!(bin_equiv, checked_mul);
for_all!(bin_equiv, checked_div);
for_all!(bin_equiv, checked_add);
for_all!(bin_equiv, checked_sub);

for_all!(bin_equiv, saturating_mul);
for_all!(bin_equiv, saturating_div);
for_all!(bin_equiv, saturating_add);
for_all!(bin_equiv, saturating_sub);

for_signed!(un_equiv, saturating_neg);
for_signed!(un_equiv, saturating_abs);
for_signed!(un_equiv, unsigned_abs);
for_signed!(un_equiv, checked_abs);



// What follow are additional tests for specific patterns from TACModSimplifier.  Much of this was generated by Claude,
// from a prompt to increase test coverage.  Sime of these are silly tests, but coverage is better than none...

#[rule]
pub fn add_negative_constant() {
    let x: i64 = nondet();
    let y: i64 = -1234;
    let rust = x.checked_add(y);
    let native = x.n_checked_add(y);
    clog!(x, y);
    cvlr_assert_eq!(rust, native);
}

#[rule]
pub fn sub_negative_constant() {
    let x: i64 = nondet();
    let y: i64 = -1234;
    let rust = x.checked_sub(y);
    let native = x.n_checked_sub(y);
    clog!(x, y);
    cvlr_assert_eq!(rust, native);
}

#[rule]
pub fn add_no_overflow_u64() {
    let x: u64 = nondet();
    let y: u64 = nondet();
    let r: u64 = x.wrapping_add(y);
    clog!(x, y);
    let no_ovf: bool = r >= x;
    cvlr_assume!(no_ovf);
    // Under the assumption r >= x, wrapping_add equals the true sum (no overflow).
    cvlr_assert!((r as u128) == (x as u128) + (y as u128));
}

#[rule]
pub fn sub_no_borrow_u64() {
    let x: u64 = nondet();
    let y: u64 = nondet();
    let r: u64 = x.wrapping_sub(y);
    clog!(x, y);
    let no_borrow: bool = r <= x;
    cvlr_assume!(no_borrow);
    // Under the assumption r <= x, wrapping_sub equals the true difference (no borrow).
    cvlr_assert!((r as u128) + (y as u128) == (x as u128));
}

#[rule]
pub fn gt_signed_to_unsigned_i64() {
    use cvlr::mathint::NativeInt;
    let x: u64 = nondet();
    let y: u64 = nondet();
    clog!(x, y);
    // NativeInt unsigned comparison on sign-extended values equals signed > on the originals.
    let x_sext = NativeInt::from(x).sext(64);
    let y_sext = NativeInt::from(y).sext(64);
    let lhs = x_sext > y_sext;
    let rhs = (x as i64) > (y as i64);
    cvlr_assert!(lhs == rhs);
}

#[rule]
pub fn ge_signed_to_unsigned_i64() {
    use cvlr::mathint::NativeInt;
    let x: u64 = nondet();
    let y: u64 = nondet();
    clog!(x, y);
    // NativeInt unsigned comparison on sign-extended values equals signed >= on the originals.
    let x_sext = NativeInt::from(x).sext(64);
    let y_sext = NativeInt::from(y).sext(64);
    let lhs = x_sext >= y_sext;
    let rhs = (x as i64) >= (y as i64);
    cvlr_assert!(lhs == rhs);
}

#[rule]
pub fn shr63_u64() {
    let x: u64 = nondet();
    clog!(x);
    let r = x >> 63;
    // Constrain the shift result at runtime so the compiler keeps the shift.
    cvlr_assume!(r == 1);
    // Discharging this requires understanding the shift's relation to bit 63.
    cvlr_assert!(x >= 1u64 << 63);
}

#[rule]
pub fn mod_sub_eq_u64() {
    let x: u64 = nondet();
    let y: u64 = nondet();
    clog!(x, y);
    let s = x.wrapping_add(y);
    let r = s.wrapping_sub(0x42);
    // Use r in multiple places to prevent (r == 0 <=> s == 0x42) folding.
    clog!(r);
    cvlr_assume!(r == 0);
    cvlr_assert!(s == 0x42);
}

#[rule]
pub fn mod_and_u64() {
    use cvlr::mathint::NativeInt;
    let x: u64 = nondet();
    let y: u64 = nondet();
    clog!(x, y);
    // wrapping_add yields explicit Mod(Add(x, y), 2^64) in TAC.
    let s: u64 = x.wrapping_add(y);
    // NativeInt::mask emits BWAnd(s, 2^64 - 1).  Combined with the wrapping_add,
    // this is exactly the mod-and shape: x.mod(2^64) & maxUnsigned(64).
    let masked: u64 = NativeInt::from(s).mask(64).into();
    clog!(masked);
    cvlr_assert!(masked == s);
}

#[rule]
pub fn sub_flip_sign_u64() {
    let x: u64 = nondet();
    let y: u64 = nondet();
    clog!(x, y);
    // The sub-flip-sign rewrite handles `Mod(Sub(x, c), 2^64)` where `c` is
    // a 2's-complement-negative constant.  LLVM aggressively canonicalizes a
    // direct `wrapping_sub(<concrete negative>)` into `wrapping_add(<positive>)`,
    // so we route the subtraction through a non-constant `y` and constrain
    // its value at the prover level.  The Sub stays in TAC; whether the
    // sub-flip-sign rewriter picks the constant up depends on how far
    // constant propagation runs before the mod-math passes.
    cvlr_assume!(y == 0xFFFFFFFFFFFFFFFE);
    let r: u64 = x.wrapping_sub(y);
    clog!(r);
    cvlr_assert!(r == x.wrapping_add(2));
}

#[rule]
pub fn signext_mod_sign_i8() {
    use cvlr::mathint::NativeInt;
    let x: u64 = nondet();
    clog!(x);
    // Sign-extend from low 8 bits via shl/arith-shr.  In TAC this is the
    // shl-mod-signext input shape; after that rewrite, leaves
    // Mod(SignExtend(0, x), 2^64).  We then need to compare against
    // maxSigned(64) without LLVM optimizing the comparison into signed
    // form; using NativeInt's own `.le` ensures the comparison stays as
    // an unsigned `Le` with the constant directly in the TAC operand.
    let shifted: u64 = x << 56;
    let arith_shifted: u64 = ((shifted as i64) >> 56) as u64;
    clog!(arith_shifted);
    let nonneg: bool = NativeInt::from(arith_shifted) <= NativeInt::from(0x7FFF_FFFF_FFFF_FFFF_u64);
    cvlr_assert!(nonneg == ((x as u8) < 128));
}

#[rule]
pub fn signext_mod_nonzero_i8() {
    use cvlr::mathint::NativeInt;
    let x: u64 = nondet();
    clog!(x);
    let shifted: u64 = x << 56;
    let arith_shifted: u64 = ((shifted as i64) >> 56) as u64;
    clog!(arith_shifted);
    // Compare against 0 via NativeInt to keep the unsigned `Gt` form.
    // `arith_shifted > 0` (unsigned) is true iff the original low byte is
    // non-zero — when the byte is negative-as-i8, the sign-extended u64 is
    // still non-zero (in fact >= 0xFFFFFFFFFFFFFF80).
    let is_pos: bool = NativeInt::from(arith_shifted) > NativeInt::from(0_u64);
    cvlr_assert!(is_pos == ((x as u8) != 0));
}
